### ISSUE TITLE
When statement for virtual machines

### ISSUE THREAD

**Issue by dzmitrykliapkou** [RedHatOfficial/ansible-role-rhel7-pci-dss#3]
tasks/main.yml
~~~
when:
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
~~~
Looks like this statement causes the task to be executed on virtual machines due to `!= "guest"` is `false` in case of VM but `!= "docker"` is `true`
Shouldn't it be `and` instead of `or` here?

**Comment by dmc5179** [comment]
Please submit PRs to the main repo. These are just downstream repos from the main content repo converted into roles.
https://github.com/ComplianceAsCode/content
